---
# tasks file for vsftpd
  - name: install vsftpd
    apt:
      name: vsftpd
      state: present

  - name: edit config vsftpd
    template: 
      src: "{{ vsftpd_config_template_path }}"
      dest: "{{ vsftpd_config_path }}"
      remote_src: yes
    notify: start vsftpd